// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function SetAppConfig(arg1) {
  return window['go']['main']['App']['SetAppConfig'](arg1);
}

export function Setting() {
  return window['go']['main']['App']['Setting']();
}
